import React, { useState, useEffect } from 'react';
import { Route, Routes, useLocation } from "react-router-dom";
import "./App.css";
import CustomerRoutes from "./Routers/CustomerRoutes";
import AdminPanel from "./Admin/AdminPanel";
import { useDispatch, useSelector } from "react-redux";
import { getUser } from "./Redux/Auth/Action";
import ChatbotButton from './Customer/Chatbot/ChatbotButton';
import ChatbotWindow from './Customer/Chatbot/ChatbotWindow';
import 'katex/dist/katex.min.css';
import stompService from './Config/stompClient';
import { receiveMessage } from './Redux/Chat/Action';
